### ISSUE TITLE
Support for Windfree mode in the A/C?

### ISSUE THREAD

**Issue by lslomczynski** [Samsung/SamsungAutomationStudio#1]
Hello,

Recently I had a Samsung Avant Windfree A/C installed.
Model: AR09TXEAAWKNEU

Either there is no support for enabling the Windfree option in the "SamsungAutomationStudio" or I could not figure it out :-/

After adding the API KEY my device reports following parameters available:
`ocf, switch, airConditionerMode, airConditionerFanMode, fanOscillationMode, temperatureMeasurement, thermostatCoolingSetpoint, relativeHumidityMeasurement, airQualitySensor, odorSensor, dustSensor, veryFineDustSensor, audioVolume, remoteControlStatus, powerConsumptionReport, demandResponseLoadControl, refresh, execute, custom.spiMode, custom.thermostatSetpointControl, custom.airConditionerOptionalMode, custom.airConditionerTropicalNightMode, custom.autoCleaningMode, custom.deviceReportStateConfiguration, custom.energyType, custom.dustFilter, custom.veryFineDustFilter, custom.deodorFilter, custom.electricHepaFilter, custom.doNotDisturbMode, custom.periodicSensing, custom.airConditionerOdorController, custom.disabledCapabilities, samsungce.driverVersion`

In the Status Node, for the airConditionerMode, there is one called "notSupported" and a set of other common ones: Heat, Heat Clean, Fan, Cool, Cool Clean and so on. Same set is listed for the Command Node. Is it this one, or maybe it is the "custom.airConditionerOptionalMode" which is inaccessible via the Command Node?

Is there any way to enable Windfree mode with SamsungAutomationStudio in Node-RED?

I am looking forward to your reply!

Regards,
Lucas.

**Comment by iamjaehun** [comment]
@lslomczynski Thank you for the issue. Let me check.

**Comment by dplaya-min** [comment]
I think Samsung Automation Studio don't supports custom capabilies. It need a update!!
https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#operation/getDevicePresentation

**Comment by dplaya-min** [comment]
I think Samsung Automation Studio don't supports custom capabilies. It need an update!!
https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#operation/getDevicePresentation

**Comment by thirtynine96** [comment]
Hi Guys,
We know which you said. AS will be updated in next release.
Thank you.

**Comment by Koma-Andrea** [comment]
Also the fan-only mode in windfree is called wind, maybe is possible to fix two problem in one shot.:
https://github.com/home-assistant/core/issues/35274

**Comment by shgood** [comment]
Hi,  @lslomczynski 
Thank you for sharing the issue.

we updated our nodes.
- support un-predefined capability by getting a capability spec. dynamically using SmartThings API 
  (e.g. custom.airConditionerOptionalMode)
- apply the latest version of SmartThings Capabilities Spec. (2020.08.19) 
- modify the way of 'Automation' authorization, using x.509 certificate
  (ref: https://smartthings.developer.samsung.com/docs/smartapps/webhook-apps.html)

Check new version,
And keep sharing issues, please.
Thank you

**Comment by lslomczynski** [comment]
@shgood - I am sorry for such a late reply! I've been using the updated version since release date and I am able to control WindFree and other "custom" modes without any issue 👍 Thank you!
