### ISSUE TITLE
Event node

### ISSUE THREAD

**Issue by RitaSghe** [Samsung/SamsungAutomationStudio#10]

**Comment by dplaya-min** [comment]
Hi. RitaSghe
If you have any inquiry, please do not hesitate to leave it.
Your comments are always appreciated.

**Comment by RitaSghe** [comment]
Hi,
my necessity is in my flow to know the status of some contact sensor or switch ....
I hope that the way are not that you explained here ...
https://sasm.developer.samsung.com/tutorials/templates/b092f96b.944da8

There must be something simpler, please explain to me how to do......

**Comment by RitaSghe** [comment]
Well,
I try this palette on my pc test with ubuntu and works ok.
I try this palette on my raspberry 4pi and when I create the node Device I have this error "TypeError: Promise.allSettled is not a function" and don't works .....

**Comment by Mavrrick** [comment]
Your error with "Invalid property or argument value, Cannot read property 'type' of null" is likely related to the version of Node.js you are running. This was determined in issue 9 as part of the problem I was experiencing. I created a test environment with Node.js 14.16 and that did seem to correct the issue.

**Comment by RitaSghe** [comment]
My raspberry has Node.js 10.24
Do you think this is the problem for this error:
"TypeError: Promise.allSettled is not a function"     ?

**Comment by Mavrrick** [comment]
This is a problem introduced with the version 1.1.0 of the pallet. The previous version would run on node.js 10.x

In my case it was. I was running the Docker image of node red and it was running that version of Node.JS. I manually installed everything on a Ubuntu VM and it worked fine with Node.14. 

One thing to take note of is that Node-Red recommends Node.js 12 today. Node.js 14 is supported but not the recommend version.

In Issue 9  were I reported this problem it was stated that while developing the pallet they use the latest version of Node.JS. Version 14 is the most recent LTS version of Node.js Hopefully they will be more careful of this in the future or atleast announce what the dependency is when they release it so we know to check before upgrading.

**Comment by lslomczynski** [comment]
> My raspberry has Node.js 10.24
> Do you think this is the problem for this error:
> "TypeError: Promise.allSettled is not a function" ?

Yes, it is. I'm running Rpi 4 too and upgraded from node 10 to 14 and problem is gone. I did this after finding out this Promise.allSettled function did not exist in node 10.

**Comment by RitaSghe** [comment]
> Yes, it is. I'm running Rpi 4 too and upgraded from node 10 to 14 and problem is gone. I did this after finding out this Promise.allSettled function did not exist in node 10.

Ok, thank you ..
Do you have a link for update node.js in raspeberry?

**Comment by oriroo** [comment]
Thanks for reporting! 
We think this is the same issue as #7. So, we'll mark this as a duplicate.

**Comment by iamjaehun** [comment]
Thanks for reporting!
We think this is the same issue as #7. So, we'll mark this as a duplicate.

**Comment by dplaya-min** [comment]
@RitaSghe

**Comment by dplaya-min** [comment]
@RitaSghe  When a device's status changes in SmartThings Cloud, you need to register a webhook as a subscriber with SmartThings Cloud to receive the status. It is called SmartApp or Automation. Is is the basic subscription mechanism for SmartThings Cloud. However, It is complicated and only a development mode is provided.
So we made the My Device node. it can also be useful to check your status by pulling.

**Comment by RitaSghe** [comment]
@lslomczynski - Ok, thank you

@dplaya-min - Ok ........, I'm asking you again, it's correct that I must set the node "My device" for each flow?

**Comment by dplaya-min** [comment]
@RitaSghe Yes, each flow need a My Device. because it is not a configuration node. We are considering changing it to a configuration node according to /issues/3. But there are no plans yet.

**Comment by RitaSghe** [comment]
Yesssss! Now everything works fine!
Thank you all for help!
Have a nice day .....
