### ISSUE TITLE
Status not giving current state

### ISSUE THREAD

**Issue by cemerich** [Samsung/SamsungAutomationStudio#2]
Hi,
when I request the status from my fridge I don't get the current state. 
For example when I'm changing the rapidFridge state on my fridge the status is still giving the old status for a long time. Also the temp isn't changing according to the new temperature.

On the other side when I send a command changing the state of the rapidFreeze to on and change it on the fridge to off again the program is changing it to on again without sending a new command.

Thats realy annoying, but maybe I'm doing something wrong!?

br. Christian

**Comment by shgood** [comment]
Hi, 
It is hard to know whether It is a problem of your device or 'Samsung Automation Studio' node with only your comment.
So, please, share the whole response of your device and node-red logs.


 * If you don't set filter condition, you can get the whole response body.
![image](https://user-images.githubusercontent.com/67676176/95287935-27c6db80-08a2-11eb-8fad-7d1d35f33546.png)

![image](https://user-images.githubusercontent.com/67676176/95287855-efbf9880-08a1-11eb-980b-68edb0e20957.png)

**Comment by shgood** [comment]
Hi,
It is hard to know whether It is the problem of your device or 'Samsung Automation Studio' nodes with only your comment.
So, please, share the device response and node-red logs.

* If you don't set filter condition, you can get the whole response body of your device.

![image](https://user-images.githubusercontent.com/67676176/95318851-0da4f180-08d2-11eb-9a7f-23e96119c33d.png)

![image](https://user-images.githubusercontent.com/67676176/95318830-0847a700-08d2-11eb-853b-93d8866f4aa6.png)

**Comment by dplaya-min** [comment]
Was the answer helpful? I will close the issue. If you have further inquiries, please leave it as a new issue. Thank you.
