### ISSUE TITLE
Access to Custom Attributes and Commands

### ISSUE THREAD

**Issue by oldironUK** [Samsung/SamsungAutomationStudio#32]
I have a device listed within my Smartthings webpage showing:

Capabilities: (eg Battery, Energy Meter, etc)
also it lists:
Custom Attributes: (eg reservePercent, reserve_pending, solarPower, etc)
and:
Custom Commands: (eg setBackupReservePercent, setBackupOnlyMode, etc)

I can successfully access the list of Capabilities in the SamsungAutomationStudio Node Red app but not the Custom Attributes or Custom Commands

How can I access/set these custom parameters?

Prior to finding this app I could also access by a direct Node Red function call using API access:

msg.headers = {}
msg.method = "GET"
msg.url = "https://api.smartthings.com/v1/devices/{deviceID}/status";
msg.headers['content-type'] = "application/json"
msg.headers['Authorization'] = "Bearer {my_Smartthings_PAT_token}"
return msg;    

Perhaps in the interim there is a version of this that could access the Custom commands??

Thanks in advance

**Comment by iamjaehun** [comment]
If you can access custom capabilities by calling the Smartthings API(/v1/devices/{deviceID}/status), you can also access them from the _Status_ node. 
This is because the Status node also uses the API to query the device status.

**Comment by oldironUK** [comment]
Thanks for your help
