### ISSUE TITLE
Any way to specify command parameters as variables or msg inputs?

### ISSUE THREAD

**Issue by Botched1** [Samsung/SamsungAutomationStudio#5]
I have an Arlo device, and one of the commands you can do is videoCapture.

videoCapture requires parameters that look like they have to be hard entered into the node. It would be great to be able to specify those as variables or msg inputs.

Example below - startTime, captureTime, etc:

![image](https://user-images.githubusercontent.com/19985320/112376889-07090b80-8cb3-11eb-8bbe-4a69d5676863.png)

**Comment by dplaya-min** [comment]
Thank you for your comments. It helps a lot to improve the code.
We plan to improve it as quickly as possible.
