### ISSUE TITLE
Suppress debug message for status node

### ISSUE THREAD

**Issue by Botched1** [Samsung/SamsungAutomationStudio#6]
Whenever I trigger a status node, it logs a message in the debug logger. If you are periodically triggering some status nodes it makes a LOT of messages. I don't see any what to turn this off?

EDIT: Remove line 577 in 101-SmartThings.js, or make it optional with another configurable node property.
NODE.warn("[SmartThings] Status :" + NODE.name);

Flow:
![image](https://user-images.githubusercontent.com/19985320/112377399-afb76b00-8cb3-11eb-8e84-de8355ee0ad5.png)

Logging is OFF on the nodes:
![image](https://user-images.githubusercontent.com/19985320/112377326-9a424100-8cb3-11eb-9544-a7efbfe9a357.png)

Debug Logs:
![image](https://user-images.githubusercontent.com/19985320/112377368-a62e0300-8cb3-11eb-9401-d9fed4bc88b4.png)

**Comment by shgood** [comment]
Hi.

A new version with added logging options has been released.

![image](https://user-images.githubusercontent.com/67676176/112640315-91549980-8e84-11eb-945a-c30dae14cfc2.png)

You can turn off unnecessary logging using the option above.

Thank you.

**Comment by Botched1** [comment]
You guys are AWESOME.
