### ISSUE TITLE
Project still Alive ?

### ISSUE THREAD

**Issue by guny74** [Samsung/SamsungAutomationStudio#65]
Hello,

Question: Is this Project still alive ? I also send an Email to the adress mentioned at the start page, but no answer ?!

Regards
   Thorsten

**Comment by hojoon22-lee** [comment]
Yes, This project is still alive. What's matter with you?

**Comment by guny74** [comment]
I sent an email asking for help for smarttag and scopes as suggested, at 16 Oktober an did not get an reply and there are now other updates at the version and the "issues". 
So what ist the best way to get help ?  The Email contact (see startpage)or open an issue here ?

**Comment by hojoon22-lee** [comment]
> I couldn't find a mail you sent. Can you describe here?

**Comment by guny74** [comment]
Hello,

I have an own Node red (3.0.2) Instance and want to use your nodes for samsung smarthings (1.1.12) .

1. Is there any documentation about the scopes I have to set to my PAT ?
2. I want to get informations about my smarttag+ which I registered to my smartthings, but all element are "null" ...any solution ?

3. I also want to see my samsung active 2 clock and my s10 smartphone under devices, but there are not in the list ? Any idea ?

Thank you for your help.

**Comment by hojoon22-lee** [comment]
Hello,
If you get PAT for smarttings node(My Device), click [personal access token pages' of Properties page.](https://account.smartthings.com/tokens), then log in with Samsung account you are using smartthings. And then you can create PAT for smartthins.
If PAT is right and then you can see your devices list on your account.
[Here is Guide of the Samsung Smartthins.](https://developer.smartthings.com/docs)
![st-pat](https://user-images.githubusercontent.com/121429410/212795954-e1a48492-c3d9-4a36-b17c-6b04c68a001e.PNG)

**Comment by hojoon22-lee** [comment]
Hello,

If you get PAT for smarttings node(My Device), click [personal access token pages' of Properties page.](https://account.smartthings.com/tokens), then log in with Samsung account you are using smartthings. And then you can create PAT for smartthins.
If PAT is right and then you can see your devices list on your account.
[Here is Guide of the Samsung Smartthins.](https://developer.smartthings.com/docs)
![st-pat](https://user-images.githubusercontent.com/121429410/212795954-e1a48492-c3d9-4a36-b17c-6b04c68a001e.PNG)

**Comment by guny74** [comment]
Hello, 

my PAT ist correct and I see my devices..e.g. smarttag or wasching maschine.
1. Smartphone and my "samsung active 2 watch" is not on the list   Why ?
2. Requesting the status of the smart tag. all elements/attributes e.g. geolocation are null.   Why ?

**Comment by hojoon22-lee** [comment]
Hi
Here is for Samsung Automation Studio that is to provide development tools and execution environment but not Samsung Smartthings. Samsung Smartthings specifics are beyond our scopes.
About Samsung SmartThings you can get more information and support [here.](https://community.smartthings.com/)

For #1 question : I have no idea the reason. You can verify your device list on Samsung SmartThings.([https://graph.api.smartthings.com/device/list](https://graph.api.smartthings.com/device/list))
For #2 question : I could find about the information you asked.
[https://community.smartthings.com/t/smarttag-not-visible-in-webinterface/228136](https://community.smartthings.com/t/smarttag-not-visible-in-webinterface/228136)

**Comment by guny74** [comment]
Hi,

hope there is no missunderstanding, in Smarthing everthing is ok.... but accessing this over node-red nodes are the problem...
and for the washing mashine from Smartthing I could access over your nodes.... but the smarthone I do not see and the smarttag+ I see, but all attributes via nod-red nodes are null..

**Comment by hojoon22-lee** [comment]
Node-RED node for Samsung SmartThings uses [SmartThings API](https://developer.smartthings.com/docs/api/public/).
If you can't see your device in the SmartThings, 'List Devices' API(Get https://api.smartthings.com/v1/devices ) doesn't response.
You can check with cURL on your computer. ( curl -X GET 'https://api.smartthings.com/v1/devices/' -H 'Authorization: Bearer <api_token>')
About the samrttag+ is referred [here.](https://community.smartthings.com/t/smarttag-on-api/225995)

**Comment by guny74** [comment]
Ok, thank you, then it is API Problem....
