### ISSUE TITLE
Getting error on Status node: ReferenceError: data is not defined

### ISSUE THREAD

**Issue by mevivek** [Samsung/SamsungAutomationStudio#75]
Node-RED version: `v3.0.2`
Node.js  version: `v16.20.1`
Linux 5.10.0-23-cloud-amd64 x64 LE
node-red-contrib-samsung-automation-studio-nodes: `1.1.15`

error message:

`8 Jul 13:12:03 - [warn] [status-device:0a557dab99da****] [SmartThings] Status :
ReferenceError: data is not defined
    at /home/developer_vivekkumar/.node-red/node_modules/node-red-contrib-samsung-automation-studio-nodes/101-SmartThings.js:682:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
8 Jul 13:12:03 - [error] [status-device:0a557dab99da601a] [error] undefined, undefined`

**Comment by jongsu2** [comment]
Hi.

A new version has been released that fixes status node error. (version 1.1.16)


Thank you.

**Comment by hojoon22-lee** [comment]
The version 1.1.16 is fixed.
