### ISSUE TITLE
SmartThings node stay disabled

### ISSUE THREAD

**Issue by dr-boss** [Samsung/SamsungAutomationStudio#87]
1. I have public IP and domain with cert.
2. I cant place to write token
3. I tested my nodered instalation from internet. Any other GET node is visible via SSL from webrowser or other service (I view GET request but verification request from studio isnt arrived. 

Resault: 
SmartThings is not able to verify the registration of the WebHook SmartApp. Please make sure your app is available and properly implemented, and verify again.
SmartThings node stay disabled

<img width="432" alt="nodered" src="https://github.com/Samsung/SamsungAutomationStudio/assets/4379499/4d149c3e-9ba7-4667-b266-1e9a2a33390f">

**Comment by jongsu2** [comment]
Hello,

Thank you for contacting Samsung Automation Studio Support.

Please share more information about your current status.

1. Does this issue still occur after refreshing the web browser?
2. What is your node-red, nodejs version?
3. How did you configure your SSL environment?
- Are you configured with a load balancer in an AWS EC2 environment?
- Is it an Ubuntu environment?

**Comment by hojoon22-lee** [comment]
We tried to reproduce this issue, but SamsungAutomationStudio was working well.
After you install SamsungAutomationStudio package, node-red needs to restart.

The below is our testing env.

30 Apr 17:06:35 - [info]
Welcome to Node-RED
===================
30 Apr 17:06:35 - [info] Node-RED version: v3.1.9
30 Apr 17:06:35 - [info] Node.js  version: v18.19.0
30 Apr 17:06:35 - [info] Linux 6.6.28+rpt-rpi-v8 arm64 LE

30 Apr 17:44:17 - [info] Installing module: node-red-contrib-samsung-automation-studio-nodes, version: 1.1.20

**Comment by jongsu2** [comment]
Hi.

A new version has been released that fixes smartthings node disabled (version 1.1.21)

Thank you.

**Comment by dr-boss** [comment]
Yes, with version 1.1.21 all work fine, thanks
